#PROBLEM:
#  2
#
#NAME: 
#  "Even Fibonacci Numbers"
# 
#PROMPT:
#  Each new term in the Fibonacci sequence is generated by adding
#  the previous two terms. By starting with 1 and 2, the first 
#  10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#  By considering the terms in the Fibonacci sequence whose values 
#  do not exceed four million, find the sum of the even-valued terms.
#
#LINK:
#  https://projecteuler.net/problem=2

sum = 0
temp1 = 1
temp2 = 2 
fib = 2
# Generate and check fibonacci numbers until the limit is exceeded
while fib <= 4000000:
   if fib % 2 == 0:  # If fib is even, add it to sum
      sum += fib
   fib = temp1 + temp2 # Generate the next fib
   temp1 = temp2  # Update/shift the temp variables
   temp2 = fib
print sum   	
